name: lamaxima_fm
description: La aplicación oficial de La Máxima 88.5 FM para Android, iOS, Web y Desktop.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Backend: Supabase
  supabase_flutter: ^2.6.0

  # Audio Streaming & Segundo plano
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-rc.8

  # Video Streaming (Live TV HLS)
  video_player: ^2.8.2
  chewie: ^1.7.5

  # Manejo de Estado
  provider: ^6.1.1

  # Utilidades UI y Fuentes
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0

  # Redes Sociales, Descargas e Internacionalización
  url_launcher: ^6.2.4
  intl: ^0.19.0
  path_provider: ^2.1.2
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
